PROGRAM _CYCLIC
(* cyclic program *)

if (moveGreiferPositive=TRUE) then
	greifer.pulseWidthCurrent			:=	greifer.pulseWidth
	greifer.periodDurationCurrent	:=	greifer.periodDuration
else if (moveGreiferNegative=TRUE) then
	greifer.pulseWidthCurrent			:=	-greifer.pulseWidth
	greifer.periodDurationCurrent	:=	greifer.periodDuration
else
	greifer.pulseWidthCurrent			:=	0
	greifer.periodDurationCurrent	:=	0
endif
END_PROGRAM

